name: reelfit
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  go_router: ^17.1.0
  http: ^1.6.0
  logging: ^1.3.0
  intl: ^0.20.2
  shared_preferences: ^2.5.4
  google_fonts: ^8.0.0
  family_bottom_sheet: ^0.1.0
  supabase_flutter: ^2.12.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
